### ISSUE TITLE
Better homepage

### ISSUE THREAD

**Issue by ghost** [Guardians-Stuff/Dashboard#1]
Better homepage that gives server invite, description of bot etc. So it wont just be a login button xD

**Comment by neeoll** [comment]
Hey do you mind if I work on this? Trying to get some experience working on open source stuff.

**Comment by ghost** [comment]
Sure, go right ahead. If you would like to talk futher about this, i am more than willing to have a chat on discord via text! Prince!#1197

**Comment by ghost** [comment]
@neeoll if any questions, dont hesitate to ask!

**Comment by neeoll** [comment]
Alright sick, I just want to double check a few things before I got to work. 
Are you cool with me using any UI libraries that aren't already part of the project? 
How exactly do you want it to look, or are there any elements you want it to have in particular, like a navbar or something?

**Comment by ghost** [comment]
> Alright sick, I just want to double check a few things before I got to work. 
> Are you cool with me using any UI libraries that aren't already part of the project? 
> How exactly do you want it to look, or are there any elements you want it to have in particular, like a navbar or something?

Sure & surprise me

**Comment by ghost** [comment]
oh wait, also on the top right make sure to include the login button.

**Comment by ghost** [comment]
Any updates @neeoll ?

**Comment by neeoll** [comment]
Alright sorry it took so long to get back to you, I got caught up with my day yesterday and only started working on it today. This is what I've thrown together, text is a placeholder obviously, and ignore the blocks of color, those are just to visualize the area that each portion of the grid takes up. After looking at it, is there anything you want in a particular place or anything like that? Text, images, anything works.
![Screenshot 2023-02-08 104708](https://user-images.githubusercontent.com/75849910/217579442-a6216205-0317-4bda-b3f2-6169d09f028c.png)

**Comment by ghost** [comment]
I kinda don't like it.  Can you do a homepage, more like the dank memer site? Like something in that sense.

**Comment by neeoll** [comment]
So something more along the lines of this?
![Screenshot 2023-02-08 121257](https://user-images.githubusercontent.com/75849910/217602840-386abf5c-6a58-48e4-98ac-f08c6b506317.png)

**Comment by ghost** [comment]
Yeah!

**Comment by ghost** [comment]
How will that changelog function work?

**Comment by neeoll** [comment]
It's only a mockup right now so I'm not sure, nothing has any functionality yet. I was going to leave that for you and whoever else you're working with since I'm not involved with the backend or anything else. But whatever y'all need me to put in as far as stuff that gets interacted with can get done, just let me know.

**Comment by ghost** [comment]
Okay! It looks good rn.

**Comment by neeoll** [comment]
I have some other stuff to tend to right now so I won't be working on it for a bit, but feel free to give any input on anything while I'm out.

**Comment by neeoll** [comment]
Fonts, colors, actual text instead of placeholders, anything goes.

**Comment by ghost** [comment]
Ok!

**Comment by ghost** [comment]
Some suggestions:

Maybe a better background image such as 
![image](https://user-images.githubusercontent.com/78247679/217675505-b3932b97-5766-4cb5-9209-40d68ffc5b3b.png)

And maybe if the user scrolls down, it will list some features along with screenshots with some animations? If you think that is a good suggestion, i am more than happy to provide screenshots with a description.

For the letters under the big Guardian word. Write something like "The most powerful and advanced multi-purpose Discord bot with a web dashboard but focused on advanced moderation to secure servers".

For the changelog, i recommend coding a system were we can write the changes in. Such as a json file and if we write stuff in there, it gets updated in the changelog tab. Same as commands, if that is no problem. The font is fine for now as were not too big on fonts.

**Comment by ghost** [comment]
that pic i provided for background, is a example. Find a nice good lofi or anime picture just like that or you can use that one but make sure its all high res please!

**Comment by ghost** [comment]
And when you code all the features, make sure it doesn't break anything else such as the login, and the dashboard features.

**Comment by neeoll** [comment]
Thanks for the added clarification, it'll make my work later on easier. Regarding the changelog, it won't really require a json file to store the data, plain html should work just fine, I'll just make a template and styles for it so that you and your team can add new changes as necessary. As for the commands, if you have a list with the commands and their functions or anything similar that you could share it would be appreciated so that I don't have to go digging through the source code for the bot to find them.

**Comment by ghost** [comment]
Do you want the bot inv so you can run /help so I don't need to list all of them? Cuz in school atm

**Comment by neeoll** [comment]
Yeah that works too

**Comment by ghost** [comment]
https://discord.com/api/oauth2/authorize?client_id=1053736067129421884&permissions=8&scope=bot%20applications.commands

**Comment by neeoll** [comment]
Thanks for letting me use the bot, got all of the commands stored in a json for easy access and I wrote the jsx in a way that should make it easy to update as the bot's functionality expands. Still tweaking some stuff and have to work on the template for the changelog but I figured I'd check in and see how you feel about the visuals. Probably gonna drop the background from the commands and changelog pages though, doesn't feel right to me.
![Screenshot 2023-02-09 142900](https://user-images.githubusercontent.com/75849910/217918368-69ec7c96-5db8-4098-ac10-266a000a828b.png)

![Screenshot 2023-02-09 142804](https://user-images.githubusercontent.com/75849910/217917591-d08eadd6-7ec4-47da-87b9-e434a477d15a.png)

**Comment by ghost** [comment]
You can always try searching for some other backgrounds that feel nice, for the commands and changelog pages! Also I love it so far! Keep up the good work haha. Also we are also hiring developers so if your interested in joining the team, lmk and it may expand your knowledge on stuff!

**Comment by ghost** [comment]
but for the navbar, i kinda dont like that there is a little gap from the top to the bar. Can you fix that? 
![image](https://user-images.githubusercontent.com/78247679/217919917-89aa8d2b-aa00-4494-adf9-1c7256683b24.png)

**Comment by ghost** [comment]
also, is it possible to change the color of the buttons on the nav bar? Like a animation, when you hover over one of the buttons on the navbar (besides the login button), it turns like blue or something? or a good color.

**Comment by neeoll** [comment]
Oh the gap was on purpose, thought it looked nice with the transparency I gave it, I'll go ahead and change that. And the buttons on the nav bar already change color when you hover over them like this:
![image](https://user-images.githubusercontent.com/75849910/217922076-1d832073-face-41c9-b2c4-4da1775bf9dd.png)

**Comment by ghost** [comment]
Wow okay! Nice job.

**Comment by ghost** [comment]
Im out of suggestions for now haha.

**Comment by neeoll** [comment]
I'll probably make the color shift gradually on hover instead of changing immediately and just polish some other stuff for now. The changelog stuff may or may not get done today, been at this for a bit already. As for joining the team, I'd have to hear more about it, but I appreciate the offer.

**Comment by ghost** [comment]
No problem and remember to take your time haha. 

About the team, the communication way would be through Discord. Our server is small as it is new and Guardian bot is somewhat half way there to verification stages on Discord. It will be a nonpaid job until i get paided somehow by someone, maybe through the disability paychecks because i am indeed disabled.

**Comment by ghost** [comment]
ngl, your a very good web developer imo.

**Comment by ghost** [comment]
Keep up the good work!

**Comment by neeoll** [comment]
I appreciate the complement since I still don't have any professional experience, but hopefully I get selected for this training-to-hire position later this month. Thanks for letting me take this on by the way!

**Comment by ghost** [comment]
Np

**Comment by ghost** [comment]
Oh also for the navbar buttons, can u space it out a bit more but not too much? They cant breathe haha

**Comment by ghost** [comment]
any updates?

**Comment by neeoll** [comment]
Yeah I have a few things, I just didn't touch it over the weekend, sorry about that. I spaced out the buttons on the navbar and moved the navbar up to the top of the screen since you said you didn't like it floating how it was before.
![Screenshot_20230213_091513](https://user-images.githubusercontent.com/75849910/218481733-7477f6f9-5d90-4c32-962b-39d656c0b63c.png)
Also started working on the changelog page, just have to do some styling for it so it doesn't look so plain.

**Comment by ghost** [comment]
Okay
